resources/bin/ballerina
resources/bin/ballerina.bat
src/main/java/org/ballerinalang/command/cmd/UpdateToolCommand.java
src/main/resources/cli-help/ballerina-update.help

> To print the dist update during dist update. If the user mistakenly uses ballerina update to update the distribution it would be better to print how to update the distribution. 
> Fixes https://github.com/ballerina-platform/ballerina-lang/issues/21416

Print dist update usage during ballerina update

---

src/main/java/org/ballerinalang/command/cmd/ListCommand.java
src/main/java/org/ballerinalang/command/util/ToolUtil.java

> This PR is to add channel separation for dist list command output and sort the listed distributions.
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/24826
- Unit tests 
> Code coverage information
- Integration tests
> Details about the test cases and coverage
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no
> Provide high-level details about the samples related to this feature
> List any other related PRs
> Describe migration steps and platforms on which migration has been tested
> List all JDK versions, operating systems, databases, and …

Sort and do channel separation for locally available distribution list

---

src/main/java/org/ballerinalang/command/cmd/Command.java
src/main/java/org/ballerinalang/command/util/OSUtils.java
src/main/java/org/ballerinalang/command/util/ToolUtil.java

> $title
Fixes https://github.com/ballerina-platform/ballerina-update-tool/issues/60 …

Fix the issue occurred during update new installed installation

---

src/main/java/org/ballerinalang/command/cmd/ListCommand.java
src/main/resources/cli-help/ballerina-dist-list.help
src/test/java/org/ballerinalang/command/ListCommandTest.java
src/test/java/org/ballerinalang/distribution/UpdateToolTest.java

Improve the bal dist list command to show the distribution version using SemVer. This enables adding extra argument to list down the entire distribution list available in a channel.  
fixes #181

Improve  bal dist list command

---

src/main/java/org/ballerinalang/command/cmd/UseCommand.java
src/test/java/org/ballerinalang/command/UseCommandTest.java

Check whether the given distribution is available to use before suggest to use 'bal dist use <distribution>'
fixes [#416](https://github.com/ballerina-platform/ballerina-distribution/issues/416)

Add distribution availability check

---

resources/bin/bal.bat

Currently when we run the `bal run "<path to ballerina file with spaces in the path>"`, it will give an error. This will fix the issue.
https://github.com/ballerina-platform/ballerina-lang/issues/34692

Fix space issue in directory path

---

resources/bin/bal.bat

`bal` command not working when there is an space in the user profile name. This fix will resolve the issue.
Wrap the `%userprofile%\.ballerina\ballerina-version` file path as well as change the file read method.
https://github.com/ballerina-platform/ballerina-lang/issues/34766

Fix space issue in user profile name

---

gradle.properties
src/main/java/org/ballerinalang/command/cmd/ListCommand.java
src/main/java/org/ballerinalang/command/util/ToolUtil.java
src/test/java/org/ballerinalang/command/UseCommandTest.java

$title
fixes #243 
These are the changes done for the output of bal dist list command
- Channels are listed from latest to oldest
- The distributions are listed from latest to oldest in each channel
- To list all the previous distributions execute 'bal dist list -a' phrase is removed and added Use 'bal dist list -a' to list all the distributions under each channel. line at the bottom of the command output when the -a flag is not used
Following will be the new output for bal dist list

Reorder the list command output

---

gradle.properties
src/main/java/org/ballerinalang/command/cmd/PullCommand.java
src/main/java/org/ballerinalang/command/cmd/UpdateCommand.java
src/main/java/org/ballerinalang/command/cmd/UpdateToolCommand.java
src/main/java/org/ballerinalang/command/util/Tool.java
src/main/java/org/ballerinalang/command/util/ToolUtil.java
src/test/java/org/ballerinalang/command/ListCommandTest.java

Prompt user to update the tool based on compatibility 

---

src/main/java/org/ballerinalang/command/util/ToolUtil.java

$title
partially fixes https://github.com/wso2-enterprise/ballerina-registry-control-plane/issues/1253

Encode `+` characters in dependency name

---

gradle.properties
resources/bin/bal
resources/bin/bal.bat

$title
partially fixes https://github.com/ballerina-platform/ballerina-distribution/issues/4716

Add Java 17 support

---

.github/workflows/test_tool_behaviour.yml
gradle.properties

This workflow enables to create a testing environment with given distribution version and a given tool version as inputs. This can be used to test the released distributions and tools in `dev` and `prod` environments. A successful run can be found 
https://github.com/udda1996/ballerina-update-tool/actions/runs/5651868015

Simulate the update tool behaviour for a given tool and a distribution

---

build.gradle
src/main/java/org/ballerinalang/command/util/ToolUtil.java

Add Update Tool server access via proxy 

---

resources/scripts/install
src/main/java/org/ballerinalang/command/util/ToolUtil.java
src/test/java/org/ballerinalang/distribution/UpdateToolTest.java

Fix JRE-17 executable permissions 

---

src/main/java/org/ballerinalang/command/util/ToolUtil.java

Current flow of update path is to download and setup distribution first and then download the dependency for the distribution then if required. In case if the dependency download was failed for some reason, the distribution will be available without the required dependency. 
In this PR we assure that the related dependency for a distribution is available before setting up the distribution. If the distribution zip is downloaded successfully but the dependency download was interrupted, the distribution won't setup and it will not be appeared in `bal dist list` as a locally available distribution. So user will need to re-run the installation command
fixes #321

Add dependency JRE availability check before setting up the distribution

---

src/main/java/org/ballerinalang/command/cmd/ListCommand.java
src/main/java/org/ballerinalang/command/util/ToolUtil.java

Include sort issue

---

src/main/java/org/ballerinalang/command/util/ToolUtil.java

For user agent, we need a Ballerina version and this will change the default Ballerina version from empty string to `0.0.0`.
This will fix the issue when we use only the ballerina-update-tool itself to pull a distribution.
Fixes #357
> Link(s) to product documentation that addresses …

Change default version to 0.0.0

---

resources/bin/bal

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
When we run the bal -v -h command on any operating system, it will simply returns the ballerina version.
Ballerina Swan Lake Beta 6
Language specification 2021R1
Update Tool 1.3.7-rc1
However when we run the ballerina version -h command, it returns help window.
Closes #199 
Display version and ballerina information post help information when running `bal -v -h` or `bal version -h` or `bal --version --help`, etc. 
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI …

Fix print content for -v -h & version for version -h as well

---

src/main/java/org/ballerinalang/command/cmd/DefaultCommand.java

In some bal --help <cmd-name> commands, after the help text, an error Unmatched argument at index 1: is printed
Get rid of the error that was caused due to the default command not expecting additional arguments
Add a `CommandLine.Parameters` such that we can take in a list of parameters avoiding the error and maybe put it to use in the future instead of modify the bal shell file
When I first found out about ballerina and started tinkering with it, I ran into this error as well, it didn't make sense to me, and neither did I think it was actually a bug, but when I found this issue, I was relieved cause I spent quite some time trying to figure out how am I typing a `--help` command wrong. XD
Fix unmatched argument log when running --help
Closes #309

Fix support for additional arguments in DefaultCommand

---

.github/workflows/build-master.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
settings.gradle

Include Gradle scan

---

resources/bin/bal
src/main/java/org/ballerinalang/command/Main.java

Fix test failure causes

---

.gitignore
src/main/java/org/ballerinalang/command/cmd/PullCommand.java
src/main/java/org/ballerinalang/command/cmd/UpdateCommand.java
src/main/java/org/ballerinalang/command/cmd/UpdateToolCommand.java
src/main/java/org/ballerinalang/command/util/ToolUtil.java

This will let the user configure a custom truststore via environment variables given below.
```
BALLERINA_CA_BUNDLE
BALLERINA_CA_PASSWORD
BALLERINA_CA_CERT
```
Fixes #384 
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus …

Support passing a custom truststore
