ballerina-platform/ballerina-update-tool

- resources/bin/ballerina
- resources/bin/ballerina.bat
> Exit the system with the non-zero status code if error occurs

- build.gradle
> Fix jar packing

- .github/workflows/build-master.yml
> Remove publishing on merge

- src/main/java/org/ballerinalang/command/cmd/PullCommand.java
- src/main/java/org/ballerinalang/command/util/ErrorUtil.java
- src/main/java/org/ballerinalang/command/util/ToolUtil.java
- src/main/resources/cli-help/ballerina-dist-pull.help
- src/main/resources/cli-help/ballerina-dist-update.help
> To fetch the dependencies of the distributions during dist pull and dist update. Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/436
> Fetch dependencies during dist pull and update 

- src/main/java/org/ballerinalang/command/util/OSUtils.java
- src/main/java/org/ballerinalang/command/util/ToolUtil.java
> Fix retreiving installed Ballerina version
> Fix retreiving installed Ballerina version

- resources/bin/ballerina
> $title. Fixes https://github.com/ballerina-platform/ballerina-lang/issues/21760
> Fix system exit code issue

- src/main/java/org/ballerinalang/command/util/OSUtils.java
> Fix user home null issue in windows
> Fix user home null issue in windows

- src/main/java/org/ballerinalang/command/util/ToolUtil.java
> Fix permission denied error when pulling new version

- src/main/java/org/ballerinalang/command/util/OSUtils.java
> Revert CentOs fix

- .gitignore
- build.gradle
- gradle.properties
- resources/bin/ballerina
- resources/bin/ballerina.bat
- resources/scripts/install
- resources/scripts/install.bat
> Fix version filtering

- .github/workflows/build-master.yml
> Include snapshot publishing

- .github/workflows/build-master.yml
> Include publish PAT

- build/bin/ballerina
> To fix when ballerina home path contains spaces.
Fixes
#https://github.com/ballerina-platform/ballerina-lang/issues/22450
> …
> Fix ballerina command issue when ballerina home path contains spaces

- src/main/java/org/ballerinalang/command/cmd/Command.java
- src/main/java/org/ballerinalang/command/cmd/ListCommand.java
- src/main/java/org/ballerinalang/command/cmd/PullCommand.java
- src/main/java/org/ballerinalang/command/cmd/RemoveCommand.java
- src/main/java/org/ballerinalang/command/cmd/UpdateCommand.java
- src/main/java/org/ballerinalang/command/cmd/UseCommand.java
- src/main/java/org/ballerinalang/command/util/Channel.java
- src/main/java/org/ballerinalang/command/util/Distribution.java
- src/main/java/org/ballerinalang/command/util/ToolUtil.java
- src/main/resources/cli-help/ballerina-dist-pull.help
- src/main/resources/cli-help/ballerina-dist-remove.help
- src/main/resources/cli-help/ballerina-dist-update.help
- src/main/resources/cli-help/ballerina-dist-use.help
> Include swan lake support for update tool
> Include swan lake support for update tool

- src/main/java/org/ballerinalang/command/util/ToolUtil.java
> Include pre prod support

- src/main/java/org/ballerinalang/command/cmd/ListCommand.java
> Include local distributions in remote list
> Include local distributions in remote list

- src/main/java/org/ballerinalang/command/util/ToolUtil.java
> Fix ballerina-version

- src/main/java/org/ballerinalang/command/util/ToolUtil.java
> Fix permission issue

- src/main/java/org/ballerinalang/command/util/ToolUtil.java
> Remove jballerina part from update message
> Remove jballerina part from update message

- .github/workflows/build-master.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- build.gradle
> Update java version to 11

- gradle.properties
- resources/bin/ballerina
- resources/bin/ballerina.bat
> Update jre 11 dependency

- src/main/java/org/ballerinalang/command/cmd/ListCommand.java
- src/main/java/org/ballerinalang/command/cmd/RemoveCommand.java
> To fix https://github.com/ballerina-platform/ballerina-update-tool/issues/41 …
> Fix dist remove -a command

- src/main/java/org/ballerinalang/command/cmd/ListCommand.java
> Refactor code

- resources/bin/ballerina
- resources/bin/ballerina.bat
> Include any jre support

- .github/workflows/build-master.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- build.gradle
> Downgrade to jdk 1.8

- src/main/java/org/ballerinalang/command/util/ToolUtil.java
> Update dev and staging central urls
> Update stage and dev central urls

- src/main/java/org/ballerinalang/command/cmd/ListCommand.java
- src/main/java/org/ballerinalang/command/util/OSUtils.java
> Fixes https://github.com/ballerina-platform/ballerina-lang/issues/26492
> Link to the PR for changes to the training content in …
> Fix dist list command to show local distributions

- src/main/java/org/ballerinalang/command/util/OSUtils.java
- src/main/java/org/ballerinalang/command/util/ToolUtil.java
> $title
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/26644 …
> Fix permission issue for dependencies

- gradle.properties
- src/main/java/org/ballerinalang/command/util/OSUtils.java
- src/main/java/org/ballerinalang/command/util/ToolUtil.java
> $title
Fixes https://github.com/ballerina-platform/ballerina-update-tool/issues/50 …
> Handle $HOME in ubuntu

- build.gradle
- src/main/java/org/ballerinalang/command/cmd/ListCommand.java
- src/main/java/org/ballerinalang/command/util/OSUtils.java
> Display locally available distributions from the distribution directory

- resources/scripts/install
- resources/scripts/install.bat
> Set env variables to bal during tool update
> Set env variables to bal during tool update

- src/main/java/org/ballerinalang/command/util/OSUtils.java
- src/main/java/org/ballerinalang/command/util/ToolUtil.java
> $title
Fixes https://github.com/ballerina-platform/ballerina-update-tool/issues/60 …
> Update current version after new installation

- resources/scripts/install
- resources/scripts/install.bat
> Clean previous ballerina commands
> Clean previous ballerina commands

- src/main/java/org/ballerinalang/command/cmd/ListCommand.java
- src/main/java/org/ballerinalang/command/util/ToolUtil.java
> Update version name from the server when online

- src/main/java/org/ballerinalang/command/cmd/FetchCommand.java
- src/main/java/org/ballerinalang/command/cmd/ListCommand.java
- src/main/java/org/ballerinalang/command/cmd/PullCommand.java
- src/main/java/org/ballerinalang/command/cmd/RemoveCommand.java
- src/main/java/org/ballerinalang/command/cmd/UpdateCommand.java
- src/main/java/org/ballerinalang/command/cmd/UpdateToolCommand.java
- src/main/java/org/ballerinalang/command/cmd/UseCommand.java
- src/main/java/org/ballerinalang/command/cmd/VersionCommand.java
- src/main/resources/cli-help/ballerina-update.help
> $title 
Fixes #66 adn #68
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
> Update ballerina to bal in help texts

- src/main/java/org/ballerinalang/command/cmd/ListCommand.java
> Modify json content

- resources/scripts/install
> Set permissions for bal inside script
> Set permissions for bal inside script

- src/main/java/org/ballerinalang/command/util/OSUtils.java
- src/main/java/org/ballerinalang/command/util/ToolUtil.java
>$title
> Fixes https://github.com/ballerina-platform/ballerina-lang/issues/28229 …
> Avoid generating unwanted file in project directory

- src/main/java/org/ballerinalang/command/util/ErrorUtil.java
- src/main/java/org/ballerinalang/command/util/ToolUtil.java
> Change ballerina reference to bal
> Change ballerina reference to bal

- .github/workflows/publish-release.yml
- build.gradle
- gradle.properties
> Improve artifact publishing

- src/main/java/org/ballerinalang/command/cmd/ListCommand.java
- src/main/java/org/ballerinalang/command/util/OSUtils.java
- src/main/java/org/ballerinalang/command/util/ToolUtil.java
> $title
Fixes https://github.com/ballerina-platform/ballerina-update-tool/issues/79 …
> Improve on handling errors during version update

- resources/bin/bal
- resources/bin/bal.bat
> Fix exit code issue

- build.gradle
- src/main/java/org/ballerinalang/command/cmd/DefaultCommand.java
> Include release plugin

- gradle.properties
> Release 0.8.15

- build.gradle
> Move lib directory into zip

- gradle.properties
> Release 0.8.16

- .github/workflows/publish-release.yml
> Combine release and publish together
> Combine release and publish together

- gradle.properties
> [Gradle Release Plugin] - new version commit:  'v0.8.18'.
> [Gradle Release Plugin] - new version commit:  'v0.8.18'.

- .github/workflows/publish-release.yml
> Include build step to release
> Include build step to release

- src/main/java/org/ballerinalang/command/util/ToolUtil.java
> Fix display text when marking version

- gradle.properties
> [Gradle Release Plugin] - new version commit:  'v0.8.19'.
> [Gradle Release Plugin] - new version commit:  'v0.8.19'.

- resources/bin/bal
- resources/bin/bal.bat
> Fix exit code issue for dist commands

- gradle.properties
> [Gradle Release Plugin] - new version commit:  'v0.8.20'.
> [Gradle Release Plugin] - new version commit:  'v0.8.20'.

- src/main/java/org/ballerinalang/command/util/ToolUtil.java
> Fixes https://github.com/ballerina-platform/ballerina-update-tool/issues/96
> Change update tool client to use v2 of API

- README.md
> Include repository badges

- src/main/java/org/ballerinalang/command/cmd/RemoveCommand.java
- src/main/java/org/ballerinalang/command/util/OSUtils.java
> Remove caches when distribution is removed
> Remove caches when distribution is removed

- resources/bin/bal
- src/main/java/org/ballerinalang/command/BallerinaCliCommands.java
- src/main/java/org/ballerinalang/command/Main.java
- src/main/java/org/ballerinalang/command/cmd/BashCommand.java
- src/main/java/org/ballerinalang/command/cmd/CompletionCommand.java
- src/main/resources/cli-help/ballerina-completion-bash.help
- src/main/resources/cli-help/ballerina-completion.help
- src/main/resources/completion-script/bal_completion.bash
- src/test/java/org/ballerinalang/command/CommandTest.java
> $title
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/21074 …
> Implement completion bash command

- src/main/resources/completion-script/bal_completion.bash
> Avoid adding space at the end of the completion

- .github/workflows/publish-release.yml
> Fix release workflow issues

- .github/workflows/publish-release.yml
> Fix job output issue

- .github/workflows/publish-release.yml
> Reorder output placement

- .github/workflows/publish-release.yml
> Fix tag version

- .github/workflows/publish-release.yml
> Fix url outputs

- .github/workflows/publish-release.yml
> Fix version output

- .github/workflows/publish-release.yml
> Fix unnecessary id

- .github/workflows/publish-release.yml
> Fix upload url output

- .github/workflows/publish-release.yml
> Remove extra tag creation

- .github/workflows/publish-release.yml
> Include separate job for upload
> Include separate job for upload

- .github/workflows/publish-release.yml
- build.gradle
> Update output version

- .github/workflows/publish-release.yml
> Update version variable

- .github/workflows/publish-release.yml
> Fix version env variable

- .github/workflows/publish-release.yml
> Include step output to job output
> Include step output to job output

- .github/workflows/publish-release.yml
- build.gradle
> Fix publish workflow

- .github/workflows/publish-release.yml
> Change release creation order
> Change release creation order

- .github/workflows/publish-release.yml
> Improve workflow name 

- .github/workflows/publish-release.yml
> Fix indentation

- src/main/java/org/ballerinalang/command/util/OSUtils.java
> Add missing hyphen in dist cache directories
> Add missing hyphen in dist cache directories

- .github/workflows/publish-release.yml
> Fix artifact name

- .github/workflows/publish-release.yml
> Fix macos asset name

- build.gradle
- resources/bin/bal
- src/main/java/org/ballerinalang/command/util/ToolUtil.java
> Fix stand alone dist bugs

- src/main/java/org/ballerinalang/command/cmd/PullCommand.java
- src/main/java/org/ballerinalang/command/util/ToolUtil.java
> Include `bal dist pull latest` support
> Include bal dist pull latest support

- gradle.properties
> Update the tool version

- src/main/java/org/ballerinalang/command/util/ToolUtil.java
> Remove trust all certs

- src/main/java/org/ballerinalang/command/BallerinaCliCommands.java
- src/main/java/org/ballerinalang/command/Main.java
- src/main/java/org/ballerinalang/command/cmd/BashCommand.java
- src/main/java/org/ballerinalang/command/cmd/CompletionCommand.java
- src/main/java/org/ballerinalang/command/cmd/ZshCommand.java
- src/main/java/org/ballerinalang/command/util/ToolUtil.java
- src/main/resources/cli-help/ballerina-completion-bash.help
- src/main/resources/cli-help/ballerina-completion-zsh.help
- src/main/resources/cli-help/ballerina-completion.help
- src/main/resources/cli-help/ballerina-dist-list.help
- src/main/resources/cli-help/ballerina-dist-pull.help
- src/main/resources/cli-help/ballerina-dist-remove.help
- src/main/resources/cli-help/ballerina-dist-update.help
- src/main/resources/cli-help/ballerina-dist-use.help
- src/main/resources/cli-help/ballerina-dist.help
- src/main/resources/cli-help/ballerina-help.help
- src/main/resources/cli-help/ballerina-update.help
- src/test/java/org/ballerinalang/command/CommandTest.java
> $title
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/29279 …
> Implement completion zsh command

- README.md
> Fix codecov badge image url

- gradle.properties
> Bump versions

- src/main/java/org/ballerinalang/command/cmd/ListCommand.java
- src/main/java/org/ballerinalang/command/util/OSUtils.java
> $title
Fixes https://github.com/ballerina-platform/ballerina-update-tool/issues/147
> Link to the PR for changes to the …
> Fix permission issue for ballerina home

- resources/bin/bal
- resources/scripts/_bal
- resources/scripts/install
- src/main/java/org/ballerinalang/command/cmd/ListCommand.java
- src/main/java/org/ballerinalang/command/util/OSUtils.java
- src/main/java/org/ballerinalang/command/util/ToolUtil.java
> $title
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/30124 …
> Add zsh completion script

- resources/scripts/install
- src/main/java/org/ballerinalang/command/cmd/PullCommand.java
- src/main/java/org/ballerinalang/command/cmd/RemoveCommand.java
- src/main/java/org/ballerinalang/command/cmd/UpdateCommand.java
- src/main/java/org/ballerinalang/command/cmd/UpdateToolCommand.java
- src/main/java/org/ballerinalang/command/util/OSUtils.java
- src/main/java/org/ballerinalang/command/util/ToolUtil.java
> If there is any latest tool version available, update it along with pull and update commands.
Fixes https://github.com/ballerina-platform/ballerina-update-tool/issues/152
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus …
> Update tool version along with pull and update commands

- resources/scripts/_bal
> $title
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/30803 …
> Update zsh completion script

- src/main/java/org/ballerinalang/command/cmd/VersionCommand.java
- src/test/java/org/ballerinalang/command/DefaultCommandTest.java
- src/test/java/org/ballerinalang/command/HelpCommandTest.java
- src/test/java/org/ballerinalang/command/VersionCommandTest.java
> $title
Related to https://github.com/ballerina-platform/ballerina-update-tool/issues/142
> Link to the PR for changes to the …
> Add more unit tests

- .github/workflows/publish-release.yml
> Fix version retrieval

- .github/workflows/publish-release.yml
> Include snapshot removal part
> Include snapshot removal part

- resources/scripts/_bal
> Update zsh script

- gradle.properties
- src/main/java/org/ballerinalang/command/util/ToolUtil.java
- src/test/java/org/ballerinalang/command/PullCommandTest.java
> Improve info message

- gradle.properties
- resources/scripts/_bal
> Fix typo in zsh completion script

- src/main/resources/cli-help/ballerina-dist-list.help
- src/main/resources/cli-help/ballerina-dist-pull.help
- src/main/resources/cli-help/ballerina-dist-remove.help
- src/main/resources/cli-help/ballerina-dist-update.help
- src/main/resources/cli-help/ballerina-dist-use.help
- src/main/resources/cli-help/ballerina-dist.help
- src/main/resources/cli-help/ballerina-help.help
- src/main/resources/cli-help/ballerina-update.help
Review the update tool CLI help text files.
> Link to the PR for changes to the training content in …
> Review the Update Tool CLI Help Text Files

- gradle.properties
- src/main/resources/cli-help/ballerina-help.help
- src/test/java/org/ballerinalang/distribution/UpdateToolTest.java
> Update test version references
> Fix failing test cases

- src/main/java/org/ballerinalang/command/util/ToolUtil.java
- src/test/java/org/ballerinalang/distribution/TestUtils.java
Fix the error message in unzipping
> Fix the error message

- src/main/java/org/ballerinalang/command/cmd/ListCommand.java
- src/main/resources/cli-help/ballerina-dist-list.help
Include '-p' instead '-pr' for pre-release flag in list command
> Update pre-release flag

- resources/bin/bal.bat
> Apply space fix

- src/main/java/org/ballerinalang/command/util/ToolUtil.java
Avoid showing the distribution fetching text for non-existing distributions.
fixes #193
> Update pull command text

- resources/bin/bal.bat
Reverts ballerina-platform/ballerina-update-tool#201
> Revert "Apply space fix"

- src/main/java/org/ballerinalang/command/cmd/ListCommand.java
- src/main/java/org/ballerinalang/command/util/ToolUtil.java
- src/main/resources/cli-help/ballerina-dist-list.help
$title
fixes #203 #204 ballerina-platform/ballerina-distribution#2496
> Change getType() logic

- gradle.properties
- resources/scripts/install
- resources/scripts/install.bat
- src/test/java/org/ballerinalang/distribution/TestUtils.java
> Remove ballerina to bal change message
> Remove ballerina to bal change message

- .github/workflows/pull-request.yml
Avoid counting ballerina updates when we are running tests on it.
> Add TEST_MODE_ACTIVE env variable

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> Upgrade gradle wrapper version

- .github/workflows/add_reason_labels.yml
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
> Add reason check workflows

- src/main/java/org/ballerinalang/command/cmd/DistributionCommand.java
- src/main/java/org/ballerinalang/command/cmd/ListCommand.java
- src/main/java/org/ballerinalang/command/cmd/PullCommand.java
- src/main/java/org/ballerinalang/command/cmd/RemoveCommand.java
- src/main/java/org/ballerinalang/command/cmd/UpdateCommand.java
- src/main/java/org/ballerinalang/command/cmd/UpdateToolCommand.java
- src/main/java/org/ballerinalang/command/cmd/UseCommand.java
- src/main/java/org/ballerinalang/command/cmd/VersionCommand.java
- src/test/java/org/ballerinalang/command/ListCommandTest.java
> Add tests to improve code coverage

- gradle.properties
- src/main/resources/cli-help/ballerina-dist.help
- src/test/java/org/ballerinalang/distribution/TestUtils.java
- src/test/java/org/ballerinalang/distribution/UpdateToolTest.java
$title
fixes ballerina-platform/ballerina-lang#36678
> Update bal dist  help text

- gradle.properties
- src/main/java/org/ballerinalang/command/cmd/ListCommand.java
- src/test/java/org/ballerinalang/command/ListCommandTest.java
> Sort distribution list according to SemVer naming

- gradle.properties
- resources/bin/bal
- resources/bin/bal.bat
> Update dependencies for JAVA_CMD

- gradle.properties
Reverts ballerina-platform/ballerina-update-tool#246
> Revert "[Automated] Sync master after 1.3.11 release"

- resources/bin/bal
> Fix a typo

- gradle.properties
- resources/bin/bal
> Reduce line count

- resources/bin/bal
> Remove older JREs

- resources/bin/bal
> Reset dependency changes

- resources/bin/bal
> Fix char count

- resources/bin/bal
> Update char count

- gradle.properties
- resources/bin/bal
> Load the bash script entirely into memory before execution

- gradle.properties
- resources/scripts/install
$title
partially fixes https://github.com/ballerina-platform/ballerina-distribution/issues/3997
> Add deleting the existing shell before copying

- resources/scripts/install
> Add permission for copied script

- resources/scripts/install
> Fix path issue

- src/main/java/org/ballerinalang/command/util/OSUtils.java
$title
partially fixes https://github.com/ballerina-platform/ballerina-distribution/issues/3997
> Change the UserAgent to contain the architecture details

- build.gradle
- gradle.properties
- resources/bin/bal
- resources/bin/bal.bat
$title
partially fixes https://github.com/ballerina-platform/ballerina-distribution/issues/4163
> Add dependency in the shell scripts

- gradle.properties
> Update version for release 1.3.14

- gradle.properties
- src/main/java/org/ballerinalang/command/cmd/PullCommand.java
> Fix pull latest command

- src/main/java/org/ballerinalang/command/util/OSUtils.java
> fix architecture check

- src/main/java/org/ballerinalang/command/util/OSUtils.java
> Update architecture identifying logic

- src/main/java/org/ballerinalang/command/util/OSUtils.java
> Update architecture detecting logic

- gradle.properties
- src/main/java/org/ballerinalang/command/cmd/PullCommand.java
- src/main/java/org/ballerinalang/command/util/ToolUtil.java
$title
fixes #291 
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.
> Add distribution validation before the permission check

- src/main/java/org/ballerinalang/command/cmd/PullCommand.java
- src/test/java/org/ballerinalang/command/PullCommandTest.java
> Sort the distribution list based on version in pull latest command

- gradle.properties
- src/main/java/org/ballerinalang/command/cmd/UpdateCommand.java
- src/main/resources/cli-help/ballerina-dist-pull.help
- src/main/resources/cli-help/ballerina-dist-remove.help
- src/main/resources/cli-help/ballerina-dist-update.help
- src/main/resources/cli-help/ballerina-dist-use.help
- src/test/java/org/ballerinalang/command/PullCommandTest.java
- src/test/java/org/ballerinalang/command/RemoveCommandTest.java
- src/test/java/org/ballerinalang/command/UpdateCommandTest.java
- src/test/java/org/ballerinalang/command/UseCommandTest.java
- src/test/java/org/ballerinalang/distribution/UpdateToolTest.java
> Update logs and help text

- src/test/java/org/ballerinalang/distribution/UpdateToolTest.java
> Add tests for 1.2.x distributions

- gradle.properties
- resources/bin/bal
- resources/bin/bal.bat
> Differentiate between 'bal dist update' and 'bal tool update'

- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- gradle.properties
- src/main/java/org/ballerinalang/command/util/ToolUtil.java
> Update gradle.properties with latest release versions

- .github/workflows/publish-release.yml
- src/test/java/org/ballerinalang/distribution/UpdateToolTest.java
> Remove a test temporarily

- gradle.properties
> Update properties for 1.4.2 release

- src/main/java/org/ballerinalang/command/cmd/ListCommand.java
- src/main/java/org/ballerinalang/command/util/ToolUtil.java
> Add a semver based sort for major channels

- resources/bin/bal
> Remove redundant arguments check

- resources/bin/bal
- src/main/java/org/ballerinalang/command/util/OSUtils.java
> Add architecture identification logic for mac into shell level

- gradle.properties
> Update latest Swan Lake version for release 1.4.3

- src/main/java/org/ballerinalang/command/util/ToolUtil.java
> Fix indexing issue in distribution list

- src/test/java/org/ballerinalang/command/RemoveCommandTest.java
> Fix remove command test

- gradle.properties
> Update latest version for 1.x channel

- src/test/java/org/ballerinalang/distribution/UpdateToolTest.java
> Fix test failure

- src/test/java/org/ballerinalang/distribution/UpdateToolTest.java
> Fix dependency availability test

- src/test/java/org/ballerinalang/distribution/TestUtils.java
> Improve getDependencyPath method

- build.gradle
- gradle.properties
- src/test/java/org/ballerinalang/distribution/TestUtils.java
- src/test/java/org/ballerinalang/distribution/UpdateToolTest.java
> Fix tests for 'bal dist remove' command

- .github/workflows/stale_check.yml
> Update the stale version

- gradle.properties
- src/test/java/org/ballerinalang/command/ListCommandTest.java
> Fix failing tests

- gradle.properties
> Update 1.2.x latest version property
> Update 1.2.x latest version property

- src/test/java/org/ballerinalang/distribution/UpdateToolTest.java
> Update 1.2.x version in the Test
> Update 1.2.x version in the Test

- src/main/java/org/ballerinalang/command/Main.java
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
Fixes: [https://github.com/ballerina-platform/ballerina-distribution/issues/415](https://github.com/ballerina-platform/ballerina-distribution/issues/415)
> Brief description of the new feature or bug fix as it will …
> Validate command arguments

- resources/bin/bal
- resources/bin/bal.bat
> Include JRE 21 support

- gradle.properties
> Update latest version

- gradle.properties
> Update latest 1.2.x version

- gradle.properties
- src/main/java/org/ballerinalang/command/util/ToolUtil.java
This will solve the executable permission set for dependency jre folder when a new jre version is pulled along with `bal dist pull <VERSION>` command.
Fixes #382
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
> Fix 'bal dist pull' failure in windows
